### PR TITLE
Fix simulator list for Xcode 10.2 beta 1.

### PR DESCRIPTION
**Pull request by SlaunchaMan**
This uses @hamchapman’s fix for the issue. Fixes [this CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/8458) for users with Xcode 10.2 beta 1 installed.

### CODE REVIEW

**Comment by dnkoutso** [comment]
Great, can you please add tests for it?

**Comment by SlaunchaMan** [comment]
@dnkoutso How’s this?

**Comment by dnkoutso** [comment]
its great. Need to run `rubocop -a` and if possible squash commits into one then add one more commit that fixes CI travis/bundler issue with this change:

```
gem install bundler -v "~> 1.17"
```

In `.travis.yml` file.

**Comment by SlaunchaMan** [comment]
@dnkoutso Will do when I get back to my computer!

**Comment by SlaunchaMan** [comment]
@dnkoutso Should be good to go!

**Comment by dnkoutso** [comment]
thank you sir!

**Pull request merged**
