### PR TITLE
A more helpful error message for missing simulators

### PR DESCRIPTION
**Pull request by radex**
This vague error message caused me a lot of pain in CocoaPods/CocoaPods#5878. I thought it was an `xcodebuild` error, while in fact it was a very simple thing to fix. This should spare future generations from this failure mode.

### CODE REVIEW

**Comment by alloy** [comment]
Will it be clear to people what “have a [OS] simulator installed” means and the steps they need to take? Can this be phrased differently to include the steps they need to perform?

**Comment by radex** [comment]
@alloy Good point. What do you think about this?

> Invalid OS `tvos`, valid values are ios, watchos. Go to Xcode and open Window -> Devices to make sure you have at least one `tvos` simulator set up. You can create a new simulator by pressing '+' in the bottom left corner of this window.

**Comment by alloy** [comment]
Maybe this could be enough?

> Ensure that Xcode -> Window -> Devices has at least one tvos simulator listed or otherwise add one.

**Comment by radex** [comment]
Ah! I like when errors first say *what* went wrong, then suggest a solution:

> Could not find a `tvos` simulator (valid values: ios, watchos). Ensure that Xcode -> Window -> Devices has at least one `tvos` simulator listed or otherwise add one.

Is that cool?

**Comment by alloy** [comment]
Yup, totally 👍 Sorry, I didn’t mean to remove that first part, that part was just a given imo.

**Comment by alloy** [comment]
@segiddins I’m unfamiliar with the CI status of this. Is the build failing because of CI specific reasons?

**Comment by segiddins** [comment]
I have no clue, maybe @neonichu would know?

**Comment by neonichu** [comment]
Looks to me as if the Travis env changed since the last build, I'll make a PR to the fix the build.

**Comment by radex** [comment]
↑ Updated the branch, passes CI now

**Comment by alloy** [comment]
Awesome 👍 Thanks, @radex!

**Pull request merged**
